# Generated by Django 5.2.3 on 2025-07-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num", models.IntegerField()),
                ("name", models.CharField()),
                ("artist", models.CharField()),
                ("lyric", models.CharField()),
                ("url", models.CharField()),
                ("pic_url", models.CharField()),
                ("artist_url", models.CharField()),
            ],
        ),
    ]
