# Generated by Django 5.2.3 on 2025-07-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MUSIC", "0002_singer"),
    ]

    operations = [
        migrations.AddField(
            model_name="singer",
            name="num",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
